import { cellToParent, latLngToCell } from "h3-js";
import type { Signal } from "./domain";
// Fictional fixtures only. Never seed these as community inventory or count as pilot evidence.
export function demoSignals(now = Date.now()): Signal[] {
  const examples = [
    [
      "sport",
      "Cầu lông tối nay, còn 2 chỗ",
      "Sân Cầu Lông Mẫu",
      "Phú Nhuận",
      106.676,
      10.803,
      30,
      "Trình độ cơ bản đến trung bình. Mang theo vợt, cùng chia tiền sân.",
      "Còn 2 chỗ",
    ],
    [
      "music",
      "Một buổi acoustic thật gần",
      "Không Gian Nhạc Mẫu",
      "Tân Bình",
      106.658,
      10.8,
      60,
      "Gặp nhau qua vài bản nhạc mộc. Hoạt động minh họa, không phải lịch diễn thật.",
      "Vào cửa tự do",
    ],
    [
      "workshop",
      "Nặn một chiếc cốc của riêng bạn",
      "Xưởng Gốm Mẫu",
      "Phú Nhuận",
      106.687,
      10.813,
      90,
      "Một buổi làm quen với đất sét. Nội dung dùng để xem thử giao diện.",
      "Nhóm nhỏ · 6 người",
    ],
    [
      "community",
      "Cà phê & chuyện cuối ngày",
      "Góc Gặp Gỡ Mẫu",
      "Gò Vấp",
      106.675,
      10.833,
      15,
      "Một chiếc bàn chung cho những cuộc chuyện trò mới. Dữ liệu minh họa.",
      "Chào đón người mới",
    ],
    [
      "sport",
      "Chạy nhẹ 3 km, ai cũng theo được",
      "Điểm Chạy Mẫu",
      "Tân Bình",
      106.643,
      10.818,
      120,
      "Pace trò chuyện, không thi đấu. Hẹn chạy này chỉ là ví dụ.",
      "Không giới hạn trình độ",
    ],
    [
      "community",
      "Đổi sách, mang về một câu chuyện",
      "Tủ Sách Mẫu",
      "Gò Vấp",
      106.655,
      10.838,
      180,
      "Mang một cuốn đã đọc và chọn một cuốn mới. Nội dung minh họa.",
      "Mang theo 1 cuốn sách",
    ],
  ] as const;
  return examples.map(
    (
      [
        category,
        title,
        place_name,
        area,
        longitude,
        latitude,
        minutes,
        description,
        capacity_note,
      ],
      index,
    ) => ({
      id: `00000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
      place_id: `10000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
      title,
      description,
      category,
      place_name,
      area,
      longitude,
      latitude,
      capacity_note,
      starts_at: new Date(now + minutes * 60_000).toISOString(),
      expires_at: new Date(now + (minutes + 90) * 60_000).toISOString(),
      confidence: "unconfirmed",
      source_label: "Dữ liệu minh họa",
      confirmation_count: 0,
      h3_parent: cellToParent(latLngToCell(latitude, longitude, 9), 6),
      is_demo: true,
    }),
  );
}
